name: Send Birthday Emails

on:
  schedule:
    - cron: '0 4 * * *' # 9:30 AM IST daily
  workflow_dispatch:

jobs:
  run-birthday-script:
    runs-on: ubuntu-latest
    environment: email-sender # 🟡 <-- Use the exact name of your environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r server/requirements.txt

      - name: Run Birthday Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python server/birthday_mailer.py
